{
  "cveMetadata": {
    "cveId": "CVE-2023-2979",
    "assignerOrgId": "1af790b2-7ee1-4545-860a-a788eba489b5",
    "state": "PUBLISHED",
    "assignerShortName": "VulDB",
    "dateReserved": "2023-05-30T13:30:37.990Z",
    "datePublished": "2023-05-30T14:00:06.300Z",
    "dateUpdated": "2024-08-02T06:41:03.961Z"
  },
  "containers": {
    "adp": [
      {
        "providerMetadata": {
          "orgId": "af854a3a-2127-422b-91ae-364da2661108",
          "shortName": "CVE",
          "dateUpdated": "2024-08-02T06:41:03.961Z"
        },
        "title": "CVE Program Container",
        "references": [
          {
            "url": "https://vuldb.com/?id.230211",
            "tags": [
              "vdb-entry",
              "technical-description",
              "x_transferred"
            ]
          },
          {
            "url": "https://vuldb.com/?ctiid.230211",
            "tags": [
              "signature",
              "permissions-required",
              "x_transferred"
            ]
          },
          {
            "url": "https://pydio.com/en/community/releases/pydio-cells/pydio-cells-enterprise-421",
            "tags": [
              "patch",
              "x_transferred"
            ]
          },
          {
            "url": "https://popalltheshells.medium.com/multiple-cves-affecting-pydio-cells-4-2-0-321e7e4712be",
            "tags": [
              "exploit",
              "x_transferred"
            ]
          }
        ]
      }
    ]
  },
  "search": "解析验收测试文案"
}